<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_media_facts_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_facts',
    'entity_type' => 'media',
    'entity_bundles' => ['facts'],
    'entity_view_modes' => ['usage', 'preview', 'search', 'embedded'],
  ]);
}
