<?php

use Drupal\degov_common\Common;
use Drupal\media_entity\MediaInterface;

/**
 * Implements hook_preprocess().
 */
function degov_media_social_media_embed_preprocess(&$variables, $hook, &$info) {
  if ($hook === 'media') {
    /* @var \Drupal\media_entity\Entity\Media $media */
    $media = $variables['elements']['#media'];
    $variables['media'] = $media;
  }

  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_social_media_embed',
    'entity_type' => 'media',
    'entity_bundles' => ['some_embed'],
    'entity_view_modes' => ['usage'],
  ]);
}

/**
 * Implements hook_preprocess_paragraph__HOOK().
 */
function degov_media_social_media_embed_preprocess_paragraph__media_reference(&$variables) {
  /** @var \Drupal\paragraphs\ParagraphInterface $paragraph */
  $paragraph = $variables['paragraph'];
  /** @var \Drupal\media_entity\MediaInterface $media */
  $media = $paragraph->field_media_reference_media->entity;

  if ($media instanceof MediaInterface && $media->bundle() === 'some_embed') {
    $variables['attributes']['class'][] = 'some-' . $media->field_some_embed_type->value;
  }
}
