<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_content_types_shared_fields_preprocess_field(&$variables) {
  $field_name = $variables['field_name'];
  // Include the shariff sharing block buttons if social media sharing is
  // enabled on the node. Appears on the bottom of both header/content paragraph.
  if (in_array($field_name, ['field_header_paragraphs', 'field_content_paragraphs'])) {
    /* @var \Drupal\node\NodeInterface $node */
    $node = $variables['element']['#object'];

    if ($node instanceof NodeInterface && $node->hasField('field_social_media') && $node->field_social_media->value == '1') {
      $variables['items'][] = [
        'content' => [
          '#theme' => 'block_shariff',
          '#blocksettings' => [],
          '#attached' => [
            'library' => [
              'degov_content_types_shared_fields/shariff-2click',
            ],
          ],
        ],
      ];
    }
  }
}
