<?php

/**
 * Next module update version is 8002.
 * All update hooks from 1.1 to 1.2 were deleted.
 * There is no upgrade path from 1.1 to 1.3, you need first to update to 1.2 and
 * then to 1.3.
 * The fresh install should have all the changes from 1.1 to 1.3.
 */

/**
 * Add preview view mode.
 */
function degov_content_types_shared_fields_update_8002() {
  \Drupal::service('degov_config.updater')->configPartialImport('degov_content_types_shared_fields');
}
