<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function degov_content_types_shared_fields_preprocess_node(&$variables) {
  // Include the shariff sharing block buttons if social media sharing is
  // enabled on the node. Appears on the bottom of both header/content paragraph.

  /* @var \Drupal\node\NodeInterface $node */
  $node = $variables['elements']['#node'];

  if ($node->hasField('field_social_media')
    && $node->field_social_media->value == '1'
    && !empty($variables['content']['shariff_field'])) {
    $variables['content']['shariff_field']['#attached']['library'] = ['degov_content_types_shared_fields/shariff-2click'];
  }
}
