<?php

/**
 * Next module update version is 8006.
 * All update hooks from 1.1 to 1.6 were deleted.
 * There is no upgrade path from 1.1 to 1.6, you need first to update to 1.2,
 * 1.3, 1.4 and then to 1.5 respectively.
 * The fresh install should have all the changes from 1.1 to 1.6.
 */

/**
 * Add asset fields.
 */
function degov_content_types_shared_fields_update_8006() {
  \Drupal::service('degov_config.module_updater')->applyUpdates('degov_content_types_shared_fields', '8006');
}