<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_uninstall().
 */
function degov_node_blog_uninstall() {
  // Removes all module type defined content when uninstalling the module.
  Common::removeContent([
    'entity_type' => 'node',
    'entity_bundles' => ['blog'],
  ]);
}

/**
 * Enable the usage view mode.
 */
function degov_node_blog_update_8001() {
    \Drupal::service('degov_config.updater')->configPartialImport('degov_node_blog');
}