<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_media_image_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_media_image',
    'entity_type' => 'media',
    'entity_bundles' => ['image'],
    'entity_view_modes' => ['thumbnail', 'usage', 'preview', 'search', 'full'],
  ]);
}


function degov_media_image_preprocess_media__image(&$variables) {
  $variables['created'] = $variables['media']->created->value;
  $variables['image_url'] = $variables['media']->url();
}