<?php

/**
 * @file
 * VSM Search module.
 */

function degov_vsm_search_theme($existing, $type, $theme, $path) {
  return [
    'vsm_search_results' => [
      'render element' => 'custom_page',
      'path' => $path . '/templates',
      'template' => 'vsm-search-results',
      'variables' => [
        'results' => NULL,
        'query' => NULL,
        'pager' => NULL,
        'lang' => NULL,
        'result_count' => NULL,
      ],
    ],
  ];
}

function degov_vsm_search_preprocess_page(array &$variables) {
  $variables['#attached']['library'][] = 'degov_vsm_search/vsm-search-assets';
}

function degov_vsm_search_preprocess_html(&$variables) {
  $route_name = Drupal::routeMatch()->getRouteName();
  if($route_name === 'degov_vsm_search.search') {
    $variables['attributes']['class'][] = str_replace('.', '_', $route_name);
  }
}
