<?php

/**
 * Next module update version is 8005.
 * All update hooks from 1.1 to 1.12 were deleted.
 * There is no upgrade path from 1.1 to 1.12, you need first to update to 1.2
 * and every minor release as well until 1.12 respectively.
 * The fresh install should have all the changes from 1.1 to 1.12.
 */

/**
 * Add title field.
 */
function degov_media_tweet_update_8005() {
  \Drupal::service('degov_config.module_updater')
    ->applyUpdates('degov_media_tweet', '8005');
}
