<?php

/**
 * Implements hook_install().
 */
function degov_search_content_install() {
  // Flush plugin caches so our facets will be shown.
  \Drupal::service('plugin.cache_clearer')->clearCachedDefinitions();
}

/**
 * Next module update version is 8002.
 * All update hooks from 1.1 to 1.2 were deleted.
 * There is no upgrade path from 1.1 to 1.3, you need first to update to 1.2 and
 * then to 1.3.
 * The fresh install should have all the changes from 1.1 to 1.3.
 */
