<?php

use Drupal\degov_common\Common;

/**
 * Implements hook_preprocess().
 */
function degov_taxonomy_media_language_preprocess(&$variables, $hook, &$info) {
  // Add template suggestions and libraries implemented in this module.
  Common::addThemeSuggestions($variables, $hook, $info, [
    'module_name' => 'degov_taxonomy_media_language',
    'entity_type' => 'taxonomy_term',
    'entity_bundles' => ['media_language'],
    'entity_view_modes' => [],
  ]);
}
